import express from 'express';
import { pool, withTransaction } from '../config/db.js';
import { resolveProductLine, validateCoupon } from '../services/commerce.js';
import { getCategories, getCoupons, getPages, getProducts, getSettings, sanitizeProduct, sanitizeSettings, saveOrder, saveProduct } from '../services/store.js';
import { makeId, orderNumber, publicToken } from '../utils/ids.js';
import { asyncHandler, created, HttpError, number, ok, parseJson } from '../utils/http.js';

const router=express.Router();
const publicOrder=order=>{const{publicToken:token,...safe}=order;return safe;};
router.get('/bootstrap',asyncHandler(async(_request,response)=>{const[products,categories,pages,settings]=await Promise.all([getProducts({publicOnly:true}),getCategories(),getPages({publicOnly:true}),getSettings()]);ok(response,{products,categories,pages,settings:sanitizeSettings(settings)});}));
router.get('/products/:slug',asyncHandler(async(request,response)=>{const[rows]=await pool.execute("SELECT data FROM products WHERE (slug=? OR id=?) AND status='active' LIMIT 1",[request.params.slug,request.params.slug]);if(!rows[0])throw new HttpError(404,'Product not found.');ok(response,sanitizeProduct(parseJson(rows[0].data,{})));}));
router.post('/coupons/validate',asyncHandler(async(request,response)=>{const code=String(request.body?.code||'').trim().toUpperCase();const subtotal=number(request.body?.subtotal);if(!code)throw new HttpError(400,'Enter a coupon code.');const[rows]=await pool.execute('SELECT data FROM coupons WHERE code=? AND active=1 LIMIT 1',[code]);const coupon=parseJson(rows[0]?.data,null);ok(response,validateCoupon(coupon,subtotal));}));
router.post('/orders',asyncHandler(async(request,response)=>{const body=request.body||{};const customer=body.customer||{};if(!String(customer.name||'').trim()||!String(customer.phone||'').trim()||!String(customer.address||'').trim())throw new HttpError(400,'Name, phone number and address are required.');if(!body.shippingAreaId)throw new HttpError(400,'Shipping area is required.');if(!body.paymentMethodId)throw new HttpError(400,'Payment method is required.');if(!Array.isArray(body.items)||!body.items.length)throw new HttpError(400,'Cart is empty.');const order=await withTransaction(async connection=>{const settings=await getSettings(connection);const shippingArea=(settings.shippingAreas||[]).find(item=>item.id===body.shippingAreaId&&item.active);const paymentMethod=(settings.paymentMethods||[]).find(item=>item.id===body.paymentMethodId&&item.enabled);if(!shippingArea)throw new HttpError(400,'Selected shipping area is unavailable.');if(!paymentMethod)throw new HttpError(400,'Selected payment method is unavailable.');if(paymentMethod.requiresTransactionId&&!String(body.transactionId||'').trim())throw new HttpError(400,'Transaction ID is required.');let subtotal=0;const orderItems=[];const changedProducts=[];for(const requested of body.items){const[rows]=await connection.execute('SELECT data FROM products WHERE id=? FOR UPDATE',[requested.productId]);if(!rows[0])throw new HttpError(400,'A cart product no longer exists.');const product=parseJson(rows[0].data,{});const line=resolveProductLine(product,requested.variantId,requested.quantity);subtotal+=line.unitPrice*line.qty;orderItems.push({id:makeId('order-item'),productId:product.id,variantId:line.variant?.id||'',name:product.name,slug:product.slug,sku:line.variant?.sku||product.productCode,image:line.image,selectedOptionLabels:line.selectedOptionLabels,quantity:line.qty,unitPrice:line.unitPrice,lineTotal:line.unitPrice*line.qty});if(product.hasVariants){product.variants=product.variants.map(item=>item.id===line.variant.id?{...item,stock:Math.max(0,number(item.stock)-line.qty)}:item);product.stock=product.variants.filter(item=>item.status==='active').reduce((sum,item)=>sum+number(item.stock),0);}else{product.stock=Math.max(0,number(product.stock)-line.qty);}product.updatedAt=new Date().toISOString();changedProducts.push(product);}
let couponResult={discount:0,freeShipping:false,code:''};let coupon=null;if(String(body.couponCode||'').trim()){const[rows]=await connection.execute('SELECT data FROM coupons WHERE code=? AND active=1 FOR UPDATE',[String(body.couponCode).trim().toUpperCase()]);coupon=parseJson(rows[0]?.data,null);couponResult=validateCoupon(coupon,subtotal);coupon.usedCount=number(coupon.usedCount)+1;await connection.execute('UPDATE coupons SET used_count=?,data=? WHERE id=?',[coupon.usedCount,JSON.stringify(coupon),coupon.id]);}
const shippingFee=couponResult.freeShipping?0:number(shippingArea.charge);const discount=Math.min(subtotal,couponResult.discount);const total=Math.max(0,subtotal-discount+shippingFee);const now=new Date().toISOString();const result={id:makeId('order'),orderNumber:orderNumber(),publicToken:publicToken(),customer:{name:String(customer.name).trim(),phone:String(customer.phone).trim(),email:String(customer.email||'').trim(),address:String(customer.address).trim()},items:orderItems,subtotal,shippingFee,shippingAreaId:shippingArea.id,shippingAreaName:shippingArea.name,couponCode:couponResult.code||'',discount,total,paymentMethodId:paymentMethod.id,paymentMethodName:paymentMethod.name,transactionId:String(body.transactionId||'').trim(),paymentStatus:paymentMethod.id==='cod'?'unpaid':'pending',shippingStatus:'unfulfilled',status:'pending',note:String(body.note||'').trim(),createdAt:now,updatedAt:now};for(const product of changedProducts)await saveProduct(product,connection);await saveOrder(result,connection);return result;});created(response,{order},'Order placed successfully.');}));
router.get('/orders/track',asyncHandler(async(request,response)=>{const query=String(request.query.query||'').trim();if(!query)throw new HttpError(400,'Enter an order number or phone number.');const[rows]=await pool.execute('SELECT data FROM orders WHERE order_number=? OR phone=? ORDER BY created_at DESC LIMIT 10',[query,query]);if(!rows.length)throw new HttpError(404,'No order found for that order number or phone number.');ok(response,rows.map(row=>publicOrder(parseJson(row.data,{}))));}));
router.get('/orders/:id',asyncHandler(async(request,response)=>{const token=String(request.query.token||'');const[rows]=await pool.execute('SELECT data FROM orders WHERE id=? AND public_token=? LIMIT 1',[request.params.id,token]);if(!rows[0])throw new HttpError(404,'Order not found or access token is invalid.');ok(response,parseJson(rows[0].data,{}));}));
export default router;
