import { pool } from '../config/db.js';
import { parseJson } from '../utils/http.js';

export async function getCategories(connection=pool){const[rows]=await connection.query('SELECT data FROM categories ORDER BY sort_order ASC,name ASC');return rows.map(row=>parseJson(row.data,{}));}
export async function getProducts({publicOnly=false,connection=pool}={}){const[rows]=await connection.query(`SELECT data FROM products ${publicOnly?"WHERE status='active'":''} ORDER BY updated_at DESC`);return rows.map(row=>parseJson(row.data,{})).map(product=>publicOnly?sanitizeProduct(product):product);}
export async function getCoupons(connection=pool){const[rows]=await connection.query('SELECT data FROM coupons ORDER BY code');return rows.map(row=>parseJson(row.data,{}));}
export async function getPages({publicOnly=false,connection=pool}={}){const[rows]=await connection.query(`SELECT data FROM cms_pages ${publicOnly?"WHERE status='published'":''} ORDER BY title`);return rows.map(row=>parseJson(row.data,{}));}
export async function getSettings(connection=pool){const[rows]=await connection.query('SELECT data FROM store_settings WHERE id=1 LIMIT 1');return parseJson(rows[0]?.data,{});}
export async function getOrders(connection=pool){const[rows]=await connection.query('SELECT data FROM orders ORDER BY created_at DESC');return rows.map(row=>parseJson(row.data,{}));}
export function sanitizeProduct(product){const{costPrice,...safe}=product;return{...safe,variants:(safe.variants||[]).map(({costPrice:variantCost,...variant})=>variant)};}
export function sanitizeSettings(settings){const{adminEmail,adminPassword,...safe}=settings||{};return safe;}
export async function saveProduct(product,connection=pool){await connection.execute(`INSERT INTO products(id,slug,product_code,category_id,subcategory_id,status,price,stock,data) VALUES(?,?,?,?,?,?,?,?,?) ON DUPLICATE KEY UPDATE slug=VALUES(slug),product_code=VALUES(product_code),category_id=VALUES(category_id),subcategory_id=VALUES(subcategory_id),status=VALUES(status),price=VALUES(price),stock=VALUES(stock),data=VALUES(data),updated_at=CURRENT_TIMESTAMP`,[product.id,product.slug,product.productCode,product.categoryId,product.subcategoryId||null,product.status,Number(product.price||0),Number(product.stock||0),JSON.stringify(product)]);return product;}
export async function saveCategory(category,connection=pool){await connection.execute(`INSERT INTO categories(id,parent_id,slug,name,active,show_in_menu,sort_order,data) VALUES(?,?,?,?,?,?,?,?) ON DUPLICATE KEY UPDATE parent_id=VALUES(parent_id),slug=VALUES(slug),name=VALUES(name),active=VALUES(active),show_in_menu=VALUES(show_in_menu),sort_order=VALUES(sort_order),data=VALUES(data),updated_at=CURRENT_TIMESTAMP`,[category.id,category.parentId||null,category.slug,category.name,category.active?1:0,category.showInMenu?1:0,Number(category.sortOrder||0),JSON.stringify(category)]);return category;}
export async function saveCoupon(coupon,connection=pool){await connection.execute(`INSERT INTO coupons(id,code,active,used_count,data) VALUES(?,?,?,?,?) ON DUPLICATE KEY UPDATE code=VALUES(code),active=VALUES(active),used_count=VALUES(used_count),data=VALUES(data),updated_at=CURRENT_TIMESTAMP`,[coupon.id,coupon.code,coupon.active?1:0,Number(coupon.usedCount||0),JSON.stringify(coupon)]);return coupon;}
export async function savePage(page,connection=pool){await connection.execute(`INSERT INTO cms_pages(id,slug,title,status,data) VALUES(?,?,?,?,?) ON DUPLICATE KEY UPDATE slug=VALUES(slug),title=VALUES(title),status=VALUES(status),data=VALUES(data),updated_at=CURRENT_TIMESTAMP`,[page.id,page.slug,page.title,page.status,JSON.stringify(page)]);return page;}
export async function saveSettings(settings,connection=pool){await connection.execute(`INSERT INTO store_settings(id,data) VALUES(1,?) ON DUPLICATE KEY UPDATE data=VALUES(data),updated_at=CURRENT_TIMESTAMP`,[JSON.stringify(settings)]);return settings;}
export async function saveOrder(order,connection=pool){await connection.execute(`INSERT INTO orders(id,order_number,phone,customer_name,status,payment_status,shipping_status,total,public_token,data) VALUES(?,?,?,?,?,?,?,?,?,?) ON DUPLICATE KEY UPDATE status=VALUES(status),payment_status=VALUES(payment_status),shipping_status=VALUES(shipping_status),total=VALUES(total),data=VALUES(data),updated_at=CURRENT_TIMESTAMP`,[order.id,order.orderNumber,order.customer.phone,order.customer.name,order.status,order.paymentStatus,order.shippingStatus,Number(order.total||0),order.publicToken,JSON.stringify(order)]);return order;}
