import { Plus, Trash2 } from 'lucide-react';
import { useEffect, useState } from 'react';
import { useStore } from '../../contexts/StoreContext';
import { makeId, safeNumber } from '../../lib/utils';
const blank={id:'',code:'',type:'percentage',value:10,minimumOrder:0,maximumDiscount:0,active:true,startDate:'',endDate:'',usageLimit:100,usedCount:0};
export default function Coupons(){
  const{coupons,loadAdmin,adminLoaded,saveCoupon,deleteCoupon}=useStore();const[form,setForm]=useState(blank);const[saving,setSaving]=useState(false);const[error,setError]=useState('');
  useEffect(()=>{if(!adminLoaded)loadAdmin().catch(()=>{});},[adminLoaded,loadAdmin]);
  const submit=async event=>{event.preventDefault();setSaving(true);setError('');try{await saveCoupon({...form,id:form.id||makeId('coupon'),code:form.code.trim().toUpperCase(),value:safeNumber(form.value),minimumOrder:safeNumber(form.minimumOrder),maximumDiscount:safeNumber(form.maximumDiscount),usageLimit:safeNumber(form.usageLimit)});setForm(blank);}catch(requestError){setError(requestError.message);}finally{setSaving(false);}};
  return <div><div className="admin-page-heading"><div><span className="eyebrow">Promotions</span><h1>Coupons</h1><p>Create percentage, fixed or free-shipping coupons.</p></div></div>{error&&<div className="error-box">{error}</div>}<div className="admin-grid-two"><section className="admin-panel"><h2>{form.id?'Edit':'Add'} Coupon</h2><form className="stack-form" onSubmit={submit}><label>Coupon Code<input required value={form.code} onChange={event=>setForm({...form,code:event.target.value.toUpperCase()})}/></label><label>Type<select value={form.type} onChange={event=>setForm({...form,type:event.target.value})}><option value="percentage">Percentage</option><option value="fixed">Fixed Amount</option><option value="free_shipping">Free Shipping</option></select></label>{form.type!=='free_shipping'&&<label>Value<input type="number" min="0" value={form.value} onChange={event=>setForm({...form,value:event.target.value})}/></label>}<label>Minimum Order<input type="number" min="0" value={form.minimumOrder} onChange={event=>setForm({...form,minimumOrder:event.target.value})}/></label>{form.type==='percentage'&&<label>Maximum Discount<input type="number" min="0" value={form.maximumDiscount} onChange={event=>setForm({...form,maximumDiscount:event.target.value})}/></label>}<div className="form-grid"><label>Start Date<input type="date" value={form.startDate} onChange={event=>setForm({...form,startDate:event.target.value})}/></label><label>End Date<input type="date" value={form.endDate} onChange={event=>setForm({...form,endDate:event.target.value})}/></label></div><label>Usage Limit<input type="number" min="0" value={form.usageLimit} onChange={event=>setForm({...form,usageLimit:event.target.value})}/></label><label className="check-card"><input type="checkbox" checked={form.active} onChange={event=>setForm({...form,active:event.target.checked})}/><span>Active</span></label><div className="button-row"><button className="btn btn-primary" disabled={saving}><Plus size={16}/>{saving?'Saving...':'Save Coupon'}</button>{form.id&&<button type="button" className="btn btn-light" onClick={()=>setForm(blank)}>Cancel</button>}</div></form></section><section className="admin-panel"><h2>Available Coupons</h2>{coupons.map(coupon=><div className="coupon-admin-row" key={coupon.id}><span><strong>{coupon.code}</strong><small>{coupon.type.replace('_',' ')} · Min ৳{coupon.minimumOrder}</small></span><b>{coupon.type==='percentage'?`${coupon.value}%`:coupon.type==='fixed'?`৳${coupon.value}`:'Free Shipping'}</b><button className="btn btn-light btn-small" onClick={()=>setForm({...coupon})}>Edit</button><button className="icon-btn danger" onClick={()=>deleteCoupon(coupon.id)}><Trash2 size={16}/></button></div>)}</section></div></div>;
}
