import { Plus, Trash2 } from 'lucide-react';
import { useEffect, useState } from 'react';
import { useStore } from '../../contexts/StoreContext';
import { makeId, slugify } from '../../lib/utils';
const blank={id:'',title:'',slug:'',content:'',status:'draft',updatedAt:''};
export default function Pages(){
  const{pages,loadAdmin,adminLoaded,savePage,deletePage}=useStore();const[form,setForm]=useState(blank);const[saving,setSaving]=useState(false);const[error,setError]=useState('');
  useEffect(()=>{if(!adminLoaded)loadAdmin().catch(()=>{});},[adminLoaded,loadAdmin]);
  const submit=async event=>{event.preventDefault();setSaving(true);setError('');try{await savePage({...form,id:form.id||makeId('page'),slug:form.slug||slugify(form.title),updatedAt:new Date().toISOString()});setForm(blank);}catch(requestError){setError(requestError.message);}finally{setSaving(false);}};
  return <div><div className="admin-page-heading"><div><span className="eyebrow">Content</span><h1>CMS Pages</h1><p>Create About, policies and custom information pages.</p></div></div>{error&&<div className="error-box">{error}</div>}<div className="admin-grid-two"><section className="admin-panel"><h2>{form.id?'Edit':'Create'} Page</h2><form className="stack-form" onSubmit={submit}><label>Title<input required value={form.title} onChange={event=>setForm({...form,title:event.target.value,slug:form.id?form.slug:slugify(event.target.value)})}/></label><label>Slug<input value={form.slug} onChange={event=>setForm({...form,slug:slugify(event.target.value)})}/></label><label>Markdown Content<textarea required rows="12" value={form.content} onChange={event=>setForm({...form,content:event.target.value})}/></label><label>Status<select value={form.status} onChange={event=>setForm({...form,status:event.target.value})}><option value="published">Published</option><option value="draft">Draft</option></select></label><div className="button-row"><button className="btn btn-primary" disabled={saving}><Plus size={16}/>{saving?'Saving...':'Save Page'}</button>{form.id&&<button type="button" className="btn btn-light" onClick={()=>setForm(blank)}>Cancel</button>}</div></form></section><section className="admin-panel"><h2>Pages</h2>{pages.map(page=><div className="cms-admin-row" key={page.id}><span><strong>{page.title}</strong><small>/page/{page.slug} · {page.status}</small></span><button className="btn btn-light btn-small" onClick={()=>setForm({...page})}>Edit</button><button className="icon-btn danger" onClick={()=>deletePage(page.id)}><Trash2 size={16}/></button></div>)}</section></div></div>;
}
